version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev  # Use a different Dockerfile for development
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=${REDIS_DB}
    volumes:
      - .:/app  # Mount the current directory into the container

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    volumes:
      - redisData:/var/lib/redis/data

volumes:
  data:
  redisData:
